name: Trend Vision Artifact Scanner
on: 
  push:
    branches: 
      - master
permissions:
  id-token: write
  contents: read
jobs:
    ArtifactScanner:
      runs-on: ubuntu-latest
      environment: DockerRegistry
      steps:
        - name: Git clone the repository
          uses: actions/checkout@v3
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2
        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2
        - name: Login to Docker Hub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        - name: Build and push
          uses: docker/build-push-action@v4
          with:
            push: true
            tags: marbsangr/django-app:45
        - name: Vision One Container Security Scan Action
          uses: trendmicro/tmas-scan-action@1.0.10
          with:
              # Mandatory
              TMAS_API_KEY: ${{ secrets.TMAS_API_KEY }}
              REGION: us-east-1
              # Optional
              SBOM: true # Saves SBOM to SBOM.json so you can export it as an artifact later.
              IMAGE: marbsangr/django-app:45 # The image need to be public or the pipeline need to have access to the private image of choice.
              # For each threshold below, select the maximum number of vulnerabilities that are acceptable.
              MAX_TOTAL: 1000
              MAX_CRITICAL: 500
              MAX_HIGH: 500
              MAX_MEDIUM: 500
              MAX_LOW: 500
              MAX_NEGLIGIBLE: 500
              MAX_UNKNOWN: 500
              SCAN_RESULT_ARTIFACT: result.json # Save as an artifact in GitHub to be able to keep the result of the scan.
        - name: 'Upload Scan Result Artifact'
          uses: actions/upload-artifact@v3
          with:
            name: scan-result
            path: result.json
            retention-days: 30
        - name: 'Upload SBOM Artifact'
          uses: actions/upload-artifact@v3
          with:
            name: sbom
            path: SBOM.json
            retention-days: 30
